### PR TITLE
Fix GH-1567: Add utf-8 encoding in DOMDocument loadHTML method

### LINKED ISSUE #1567: Different languages not showing properly
We need to add `<?xml encoding="utf-8" ?>` while using `DOMDocument` class.

Without adding utf-8 encoding.
Screenshot 2020-03-03 at 5 04 21 PM

With utf-8 encoding
Screenshot 2020-03-03 at 5 05 46 PM

### PR DESCRIPTION
**Pull request by SID177**
Prepend `<?xml encoding="utf-8" ?>` with activity text in loadHTML method of DOMDocument's class.
Fix #1567

### CODE REVIEW

File: app/main/controllers/activity/RTMediaBuddyPressActivity.php [hunk 1]
```diff
@@ -108,7 +108,8 @@ public function bp_activity_truncate_entry( $excerpt, $text, $readmore ) {
 		$dom = new DOMDocument();
 		// DOMDocument gives error on html5 tags, so we need to disable errors.
 		libxml_use_internal_errors( true );
-		$dom->loadHTML( $text );
+		// Use utf-8 encoding for different languages.
+		$dom->loadHTML( '<?xml encoding="utf-8" ?>' . $text );
```
Comment (abhijitrakas) [inline app/main/controllers/activity/RTMediaBuddyPressActivity.php]:
```suggestion
		$dom->loadHTML( '<?xml encoding="utf-8" ?>'  );
		$dom->loadHTML($text);
```
Can we write it like ☝️

Comment (SID177) [reply app/main/controllers/activity/RTMediaBuddyPressActivity.php]: Doesn't work as expected. I think we can loadHTML only once.
